#!/usr/bin/env bash
# Creates a new app from the installed Flutter's own `flutter create` template that depends on
# becklink_flutter (the repository root) by path, the way a customer on that Flutter version adds the SDK.
# CI uses it on the oldest supported Flutter (3.27, owner decision D6), where the example app
# cannot build: the example uses the current template and Dart ^3.12.
#
# The app calls the public API, so a release build compiles the SDK's Dart code with that Flutter
# as well as its Kotlin or Swift code.
#
# CI only (GitHub Actions, Linux and macOS), like the other scripts under .github/.
# Usage: compat-app.sh <android|ios> <new app directory>
set -euo pipefail

usage() {
  echo "Usage: $0 <android|ios> <new app directory>" >&2
  exit 2
}

fail() {
  echo "::error::$*" >&2
  exit 1
}

[ "$#" -eq 2 ] || usage
platform="$1"
app_dir="$2"
case "$platform" in
  android | ios) ;;
  *) usage ;;
esac
[ ! -e "$app_dir" ] || fail "$app_dir already exists."

sdk_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

flutter create --no-pub --platforms="$platform" --org app.becklink.ci \
  --project-name becklink_compat_app "$app_dir"
cd "$app_dir"

# The template's minimum OS versions are below the SDK's (Android API 23, iOS 15; owner decision
# D4), so raise them as every app that adds the SDK must (README.md, "Platform setup").
case "$platform" in
  android)
    # Flutter 3.27's template has `minSdk = flutter.minSdkVersion` (API 21).
    perl -pi -e 's/\bflutter\.minSdkVersion\b/23/g' android/app/build.gradle*
    grep -Eq 'minSdk(Version)?[[:space:]]*=?[[:space:]]*23([^0-9]|$)' android/app/build.gradle* ||
      fail "Could not set minSdk 23 in the template's android/app/build.gradle."
    ;;
  ios)
    # The Runner target's deployment target; the Podfile follows after `flutter pub add` below.
    pbxproj=ios/Runner.xcodeproj/project.pbxproj
    target='IPHONEOS_DEPLOYMENT_TARGET = 15.0;'
    perl -pi -e "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;/${target}/g" "$pbxproj"
    grep -qF "$target" "$pbxproj" ||
      fail "The template's $pbxproj sets no IPHONEOS_DEPLOYMENT_TARGET."
    if grep -F 'IPHONEOS_DEPLOYMENT_TARGET = ' "$pbxproj" | grep -vqF "$target"; then
      fail "Could not set the iOS deployment target 15.0 in $pbxproj."
    fi
    ;;
esac

flutter pub add "becklink_flutter:{\"path\":\"$sdk_dir\"}"

# On macOS, resolving the first iOS plugin writes ios/Podfile, whose platform line is commented
# out (CocoaPods would then take the Runner target's deployment target). Set it as the README
# tells CocoaPods apps to, so this job builds the documented setup.
if [ "$platform" = ios ]; then
  podfile=ios/Podfile
  [ -f "$podfile" ] || fail "flutter pub add did not create $podfile."
  perl -pi -e "s/^[#[:space:]]*platform :ios, '[0-9.]+'.*\$/platform :ios, '15.0'/" "$podfile"
  grep -Eq "^platform :ios, '15\\.0'\$" "$podfile" ||
    fail "Could not set platform :ios, '15.0' in $podfile."
fi

# The template's widget test refers to the counter app that main.dart no longer contains.
rm -rf test

cat > lib/main.dart <<'DART'
// Generated by .github/scripts/compat-app.sh. Uses the public API so that a release
// build compiles the SDK's Dart code with this Flutter version. Never run.
import 'package:becklink_flutter/becklink_flutter.dart';
import 'package:flutter/widgets.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await BeckLink.instance.configure(apiKey: 'pk_test_compat_app_never_run');
  BeckLink.instance.onLink.listen((LinkEvent link) {});
  runApp(const SizedBox.shrink());
}
DART

echo "Created $app_dir ($platform) with becklink_flutter from $sdk_dir."
